# Generated by Django 5.2.15 on 2026-06-03 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('birthday', 'Aniversário'), ('foundation', 'Fundação')], max_length=20, verbose_name='Tipo da mensagem')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('error', 'Erro')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('destinatario_tipo', models.CharField(choices=[('customer', 'Cliente'), ('supplier', 'Fornecedor')], max_length=20, verbose_name='Tipo de destinatário')),
                ('destinatario_id', models.PositiveBigIntegerField(verbose_name='ID do destinatário')),
                ('destinatario_nome', models.CharField(max_length=180, verbose_name='Nome do destinatário')),
                ('destinatario_email', models.EmailField(max_length=254, verbose_name='Email do destinatário')),
                ('destinatario_tipo_pessoa', models.CharField(blank=True, max_length=20, verbose_name='Tipo de pessoa')),
                ('assunto', models.CharField(max_length=180, verbose_name='Assunto')),
                ('corpo', models.TextField(verbose_name='Corpo')),
                ('erro', models.TextField(blank=True, verbose_name='Erro')),
                ('ano_referencia', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Ano de referência')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Histórico de mensagem',
                'verbose_name_plural': 'Histórico de mensagens',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tipo', 'status', 'ano_referencia'], name='communicati_tipo_a07773_idx'), models.Index(fields=['destinatario_tipo', 'destinatario_id'], name='communicati_destina_dfda4b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'sent'), ('tipo__in', ['birthday', 'foundation']), ('ano_referencia__isnull', False)), fields=('tipo', 'destinatario_tipo', 'destinatario_id', 'ano_referencia'), name='unique_sent_anniversary_message_per_year')],
            },
        ),
    ]
