# Generated by Django 5.2.15 on 2026-06-03 17:55

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_TEMPLATES = [
    {
        'nome': 'Aniversário - Pessoa física',
        'tipo': 'customer_birthday_physical',
        'assunto': 'Feliz aniversário, {{ nome }}!',
        'corpo': '<p>Olá, {{ nome }}!</p><p>Hoje é o seu dia, e toda a equipe MotorMind deseja muita saúde, felicidade e sucesso.</p><p>Parabéns pelo seu aniversário!</p>',
        'padrao': True,
    },
    {
        'nome': 'Fundação - Pessoa jurídica',
        'tipo': 'customer_foundation_legal',
        'assunto': 'Parabéns pelo aniversário da {{ nome }}!',
        'corpo': '<p>Olá, {{ nome }}!</p><p>Hoje celebramos a data de fundação da sua empresa.</p><p>A equipe MotorMind deseja muitos anos de crescimento, bons negócios e sucesso.</p>',
        'padrao': True,
    },
    {
        'nome': 'Comunicado manual',
        'tipo': 'manual',
        'assunto': 'Comunicado MotorMind',
        'corpo': '<p>Olá, {{ nome }}!</p><p>Escreva aqui sua mensagem.</p>',
        'padrao': False,
    },
]


def create_default_templates(apps, schema_editor):
    MessageTemplate = apps.get_model('communications', 'MessageTemplate')
    for template_data in DEFAULT_TEMPLATES:
        MessageTemplate.objects.get_or_create(
            tipo=template_data['tipo'],
            nome=template_data['nome'],
            defaults={
                'assunto': template_data['assunto'],
                'corpo': template_data['corpo'],
                'ativo': True,
                'padrao': template_data['padrao'],
            },
        )


def remove_default_templates(apps, schema_editor):
    MessageTemplate = apps.get_model('communications', 'MessageTemplate')
    names = [template_data['nome'] for template_data in DEFAULT_TEMPLATES]
    MessageTemplate.objects.filter(nome__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('customer_birthday_physical', 'Aniversário - Cliente pessoa física'), ('customer_foundation_legal', 'Fundação - Cliente pessoa jurídica'), ('manual', 'Manual / Outro')], db_index=True, max_length=40, verbose_name='Tipo')),
                ('assunto', models.CharField(max_length=180, verbose_name='Assunto')),
                ('corpo', models.TextField(verbose_name='Corpo')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo?')),
                ('padrao', models.BooleanField(db_index=True, default=False, verbose_name='Template padrão?')),
                ('excluido_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Template de mensagem',
                'verbose_name_plural': 'Templates de mensagens',
                'ordering': ['tipo', 'nome'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True), ('excluido_em__isnull', True), ('padrao', True)), fields=('tipo',), name='unique_active_default_message_template_by_type')],
            },
        ),
        migrations.AddField(
            model_name='messagelog',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos', to='communications.messagetemplate', verbose_name='Template usado'),
        ),
        migrations.RunPython(create_default_templates, remove_default_templates),
    ]
