# Generated by Django 5.2.15 on 2026-06-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_messagetemplate_messagelog_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviar_aniversario_pessoa_fisica', models.BooleanField(default=True, help_text='Quando desabilitado, o comando automático não envia emails de aniversário para clientes pessoa física.', verbose_name='Enviar aniversário para pessoa física?')),
                ('enviar_fundacao_pessoa_juridica', models.BooleanField(default=True, help_text='Quando desabilitado, o comando automático não envia emails de fundação para clientes pessoa jurídica.', verbose_name='Enviar fundação para pessoa jurídica?')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração de mensagens',
                'verbose_name_plural': 'Configurações de mensagens',
            },
        ),
    ]
