# Generated by Django 5.2.15 on 2026-06-04 14:50

from django.db import migrations, models



def create_default_work_order_approval_template(apps, schema_editor):
    MessageTemplate = apps.get_model('communications', 'MessageTemplate')
    MessageTemplate.objects.get_or_create(
        tipo='work_order_approval',
        padrao=True,
        excluido_em__isnull=True,
        defaults={
            'nome': 'Orçamento / aprovação da OS - padrão',
            'assunto': 'Orçamento da OS {{ ordem_servico.codigo }} aguardando aprovação',
            'corpo': '<p>Olá, {{ nome }}!</p><p>O orçamento <strong>{{ orcamento.codigo }}</strong> da OS <strong>{{ ordem_servico.codigo }}</strong> está aguardando sua aprovação.</p><p>Total do orçamento: <strong>{{ valor_total }}</strong>.</p><p>Acesse: <a href="{{ link_aprovacao }}">{{ link_aprovacao }}</a></p>',
            'ativo': True,
        },
    )


def remove_default_work_order_approval_template(apps, schema_editor):
    MessageTemplate = apps.get_model('communications', 'MessageTemplate')
    MessageTemplate.objects.filter(tipo='work_order_approval', nome='Orçamento / aprovação da OS - padrão').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_work_order_status_messages'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messagelog',
            new_name='communicati_ordem_s_315fbc_idx',
            old_name='communicatio_ordem_s_3d8b0f_idx',
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='tipo',
            field=models.CharField(choices=[('manual', 'Manual'), ('birthday', 'Aniversário'), ('foundation', 'Fundação'), ('work_order_status', 'Status da OS'), ('work_order_approval', 'Orçamento / aprovação da OS')], max_length=20, verbose_name='Tipo da mensagem'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='tipo',
            field=models.CharField(choices=[('customer_birthday_physical', 'Aniversário - Cliente pessoa física'), ('customer_foundation_legal', 'Fundação - Cliente pessoa jurídica'), ('work_order_status', 'Mudança de status da OS'), ('work_order_approval', 'Orçamento / aprovação da OS'), ('manual', 'Manual / Outro')], db_index=True, max_length=40, verbose_name='Tipo'),
        ),
        migrations.RunPython(create_default_work_order_approval_template, remove_default_work_order_approval_template),
    ]
