# Generated by Django 5.2.15 on 2026-06-04 15:07

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_APPROVAL_SUBJECT = 'Orçamento da OS {{ ordem_servico.codigo }} aguardando aprovação'
DEFAULT_APPROVAL_BODY = (
    '<p>Olá, {{ nome }}!</p>'
    '<p>O orçamento <strong>{{ orcamento.codigo }}</strong> da OS '
    '<strong>{{ ordem_servico.codigo }}</strong> está aguardando sua aprovação.</p>'
    '<p>Total do orçamento: <strong>{{ valor_total }}</strong>.</p>'
    '<p>Acesse: <a href="{{ link_aprovacao }}">{{ link_aprovacao }}</a></p>'
)


def ensure_approval_template_and_settings(apps, schema_editor):
    MessageTemplate = apps.get_model('communications', 'MessageTemplate')
    MessageSettings = apps.get_model('communications', 'MessageSettings')

    template = MessageTemplate.objects.filter(
        tipo='work_order_approval',
        padrao=True,
        ativo=True,
        excluido_em__isnull=True,
    ).first()

    if template is None:
        template = MessageTemplate.objects.filter(
            tipo='work_order_approval',
            ativo=True,
            excluido_em__isnull=True,
        ).order_by('id').first()

    if template is None:
        template = MessageTemplate.objects.create(
            nome='Orçamento / aprovação da OS - padrão',
            tipo='work_order_approval',
            assunto=DEFAULT_APPROVAL_SUBJECT,
            corpo=DEFAULT_APPROVAL_BODY,
            ativo=True,
            padrao=True,
        )
    elif not template.padrao:
        MessageTemplate.objects.filter(
            tipo='work_order_approval',
            padrao=True,
            ativo=True,
            excluido_em__isnull=True,
        ).exclude(pk=template.pk).update(padrao=False)
        template.padrao = True
        template.save(update_fields=['padrao', 'atualizado_em'])

    if not MessageSettings.objects.exists():
        MessageSettings.objects.create(
            id=1,
            enviar_aniversario_pessoa_fisica=True,
            enviar_fundacao_pessoa_juridica=True,
            enviar_status_os=False,
            template_orcamento_os=template,
        )
    else:
        MessageSettings.objects.filter(template_orcamento_os__isnull=True).update(template_orcamento_os=template)


def clear_approval_template_from_settings(apps, schema_editor):
    MessageSettings = apps.get_model('communications', 'MessageSettings')
    MessageSettings.objects.update(template_orcamento_os=None)


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_work_order_approval_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesettings',
            name='template_orcamento_os',
            field=models.ForeignKey(blank=True, help_text='Template usado no email enviado quando a OS gera um orçamento para aprovação. Se ficar vazio, será usado o template padrão deste tipo.', limit_choices_to={'tipo': 'work_order_approval'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='communications.messagetemplate', verbose_name='Template de orçamento / aprovação da OS'),
        ),
        migrations.RunPython(ensure_approval_template_and_settings, clear_approval_template_from_settings),
    ]
