# Generated by Django 5.2.15 on 2026-06-03 19:50

import core.money
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models



def seed_units(apps, schema_editor):
    UnitOfMeasure = apps.get_model('stock', 'UnitOfMeasure')
    units = [
        ('Unidade', 'UN', False),
        ('Peça', 'PC', False),
        ('Caixa', 'CX', False),
        ('Jogo', 'JG', False),
        ('Par', 'PAR', False),
        ('Litro', 'L', True),
        ('Mililitro', 'ML', True),
        ('Quilograma', 'KG', True),
        ('Grama', 'G', True),
        ('Metro', 'M', True),
        ('Centímetro', 'CM', True),
        ('Hora', 'H', True),
    ]
    for nome, sigla, permite_fracionado in units:
        UnitOfMeasure.objects.get_or_create(
            sigla=sigla,
            defaults={'nome': nome, 'permite_fracionado': permite_fracionado, 'ativo': True},
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=12, unique=True, verbose_name='Sigla')),
                ('permite_fracionado', models.BooleanField(default=True, verbose_name='Permite fracionado?')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Unidade de medida',
                'verbose_name_plural': 'Unidades de medida',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo?')),
                ('excluido_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True), ('excluido_em__isnull', True)), fields=('nome',), name='unique_active_brand_name')],
            },
        ),
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo?')),
                ('excluido_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria de estoque',
                'verbose_name_plural': 'Categorias de estoque',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True), ('excluido_em__isnull', True)), fields=('nome',), name='unique_active_stock_category_name')],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo?')),
                ('excluido_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('peca', 'Peça'), ('insumo', 'Insumo')], default='peca', max_length=20, verbose_name='Tipo')),
                ('sku', models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True, verbose_name='SKU')),
                ('nome', models.CharField(max_length=180, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Estoque mínimo')),
                ('preco_custo', core.money.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Preço de custo')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='stock.brand', verbose_name='Marca')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='stock.stockcategory', verbose_name='Categoria')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='stock.unitofmeasure', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Peça/Insumo',
                'verbose_name_plural': 'Peças e insumos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste_positivo', 'Ajuste positivo'), ('ajuste_negativo', 'Ajuste negativo')], max_length=30, verbose_name='Tipo de movimentação')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade')),
                ('quantidade_assinada', models.DecimalField(decimal_places=3, editable=False, max_digits=12, verbose_name='Quantidade assinada')),
                ('saldo_apos_movimentacao', models.DecimalField(decimal_places=3, editable=False, max_digits=12, verbose_name='Saldo após movimentação')),
                ('custo_unitario', core.money.MoneyField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Custo unitário')),
                ('valor_total', core.money.MoneyField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor total')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='stock.inventoryitem', verbose_name='Peça/Insumo')),
            ],
            options={
                'verbose_name': 'Movimentação de estoque',
                'verbose_name_plural': 'Movimentações de estoque',
                'ordering': ['-criado_em', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('excluido_em__isnull', True)), fields=('nome', 'categoria', 'marca'), name='unique_active_inventory_item_by_name_category_brand'),
        ),
        migrations.RunPython(seed_units, migrations.RunPython.noop),
    ]
