# Generated by ChatGPT on 2026-06-03

from decimal import Decimal, ROUND_HALF_UP

from django.core.validators import MinValueValidator
from django.db import migrations, models


def _to_int(value, minimum=0):
    if value is None:
        return minimum
    decimal_value = Decimal(str(value))
    integer_value = int(decimal_value.to_integral_value(rounding=ROUND_HALF_UP))
    return max(integer_value, minimum)


def _to_signed_int(value):
    if value is None:
        return 0
    decimal_value = Decimal(str(value))
    return int(decimal_value.to_integral_value(rounding=ROUND_HALF_UP))


def normalize_stock_quantities(apps, schema_editor):
    InventoryItem = apps.get_model('stock', 'InventoryItem')
    StockMovement = apps.get_model('stock', 'StockMovement')

    for item in InventoryItem.objects.all().only('pk', 'estoque_minimo'):
        item.estoque_minimo = _to_int(item.estoque_minimo, minimum=0)
        item.save(update_fields=['estoque_minimo'])

    for movement in StockMovement.objects.all().only(
        'pk',
        'quantidade',
        'quantidade_assinada',
        'saldo_apos_movimentacao',
    ):
        movement.quantidade = _to_int(movement.quantidade, minimum=1)
        movement.quantidade_assinada = _to_signed_int(movement.quantidade_assinada)
        movement.saldo_apos_movimentacao = _to_int(movement.saldo_apos_movimentacao, minimum=0)
        movement.save(update_fields=['quantidade', 'quantidade_assinada', 'saldo_apos_movimentacao'])


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stockmovement_fornecedor'),
    ]

    operations = [
        migrations.RunPython(normalize_stock_quantities, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='inventoryitem',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0, validators=[MinValueValidator(0)], verbose_name='Estoque mínimo'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantidade',
            field=models.PositiveIntegerField(validators=[MinValueValidator(1)], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantidade_assinada',
            field=models.IntegerField(editable=False, verbose_name='Quantidade assinada'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='saldo_apos_movimentacao',
            field=models.PositiveIntegerField(editable=False, verbose_name='Saldo após movimentação'),
        ),
    ]
