# Generated by ChatGPT on 2026-06-04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import core.money


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_vehicle'),
        ('operations', '0010_workshop_capacity'),
        ('stock', '0003_integer_quantities'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo?')),
                ('excluido_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo', models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Código')),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('automatico_os', 'Automático por OS')], db_index=True, default='manual', max_length=30, verbose_name='Origem')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('solicitado', 'Solicitado'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('recebido_em', models.DateTimeField(blank=True, null=True, verbose_name='Recebido em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('fornecedor', models.ForeignKey(blank=True, help_text='Obrigatório para receber o pedido e dar entrada no estoque.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='core.supplier', verbose_name='Fornecedor')),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra', to='operations.workorder', verbose_name='OS de origem')),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por')),
            ],
            options={
                'verbose_name': 'Pedido de compra',
                'verbose_name_plural': 'Pedidos de compra',
                'ordering': ['-criado_em', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('custo_unitario', core.money.MoneyField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Custo unitário')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido_compra', to='stock.inventoryitem', verbose_name='Peça/Insumo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='stock.purchaseorder', verbose_name='Pedido de compra')),
            ],
            options={
                'verbose_name': 'Item do pedido de compra',
                'verbose_name_plural': 'Itens do pedido de compra',
                'ordering': ['item__nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(fields=('pedido', 'item'), name='unique_purchase_order_item'),
        ),
    ]
