# Generated by ChatGPT for MotorMind

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_inventoryitem_preco_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(
                'Código da peça/SKU',
                blank=True,
                db_index=True,
                max_length=60,
                null=True,
                unique=True,
            ),
        ),
    ]
