# Generated by Django 5.2.15 on 2026-06-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('aplicacao', models.CharField(choices=[('cliente', 'Cliente'), ('fornecedor', 'Fornecedor')], max_length=20, verbose_name='Aplicação')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['aplicacao', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('nome', 'aplicacao'), name='unique_category_by_audience')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('fisica', 'Pessoa física'), ('juridica', 'Pessoa jurídica')], max_length=10, verbose_name='Tipo de pessoa')),
                ('nome_razao_social', models.CharField(max_length=180, verbose_name='Nome / Razão social')),
                ('documento', models.CharField(max_length=18, unique=True, verbose_name='CPF / CNPJ')),
                ('data_nascimento_fundacao', models.DateField(verbose_name='Nascimento / Fundação')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=180, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=120, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=120, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=120, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('aceita_marketing', models.BooleanField(default=False, verbose_name='Aceita marketing?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categorias', models.ManyToManyField(blank=True, limit_choices_to={'aplicacao': 'cliente', 'ativa': True}, related_name='clientes', to='core.category', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome_razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('fisica', 'Pessoa física'), ('juridica', 'Pessoa jurídica')], max_length=10, verbose_name='Tipo de pessoa')),
                ('nome_razao_social', models.CharField(max_length=180, verbose_name='Nome / Razão social')),
                ('documento', models.CharField(max_length=18, unique=True, verbose_name='CPF / CNPJ')),
                ('data_nascimento_fundacao', models.DateField(verbose_name='Nascimento / Fundação')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=180, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=120, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=120, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=120, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('aceita_marketing', models.BooleanField(default=False, verbose_name='Aceita marketing?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categorias', models.ManyToManyField(blank=True, limit_choices_to={'aplicacao': 'fornecedor', 'ativa': True}, related_name='fornecedores', to='core.category', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome_razao_social'],
            },
        ),
    ]
