# Generated by Django 5.2.15 on 2026-06-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='data_nascimento_fundacao',
            field=models.DateField(blank=True, null=True, verbose_name='Nascimento / Fundação'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='documento',
            field=models.CharField(blank=True, db_index=True, max_length=18, null=True, verbose_name='CPF / CNPJ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='data_nascimento_fundacao',
            field=models.DateField(blank=True, null=True, verbose_name='Nascimento / Fundação'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='documento',
            field=models.CharField(blank=True, db_index=True, max_length=18, null=True, verbose_name='CPF / CNPJ'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('documento__isnull', False), models.Q(('documento', ''), _negated=True)), fields=('documento',), name='unique_customer_documento_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('documento__isnull', False), models.Q(('documento', ''), _negated=True)), fields=('documento',), name='unique_supplier_documento_not_blank'),
        ),
    ]
