# Generated by ChatGPT on 2026-06-03

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customer_data_nascimento_fundacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='excluido_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluída em'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='customer',
            name='excluido_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='excluido_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_by_audience',
        ),
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_customer_documento_not_blank',
        ),
        migrations.RemoveConstraint(
            model_name='supplier',
            name='unique_supplier_documento_not_blank',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(
                fields=('nome', 'aplicacao'),
                condition=Q(excluido_em__isnull=True),
                name='unique_active_category_by_audience',
            ),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(
                fields=('documento',),
                condition=Q(ativo=True) & Q(excluido_em__isnull=True) & Q(documento__isnull=False) & ~Q(documento=''),
                name='unique_active_customer_documento_not_blank',
            ),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(
                fields=('documento',),
                condition=Q(ativo=True) & Q(excluido_em__isnull=True) & Q(documento__isnull=False) & ~Q(documento=''),
                name='unique_active_supplier_documento_not_blank',
            ),
        ),
    ]
