# Generated by Django 5.2.15 on 2026-06-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_soft_delete_defaults_and_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='categorias',
            field=models.ManyToManyField(blank=True, limit_choices_to={'aplicacao': 'cliente', 'ativa': True, 'excluido_em__isnull': True}, related_name='clientes', to='core.category', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='categorias',
            field=models.ManyToManyField(blank=True, limit_choices_to={'aplicacao': 'fornecedor', 'ativa': True, 'excluido_em__isnull': True}, related_name='fornecedores', to='core.category', verbose_name='Categorias'),
        ),
    ]
