# Generated by Django 5.2.15 on 2026-06-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customer_categorias_alter_supplier_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bairro',
            field=models.CharField(blank=True, max_length=120, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cidade',
            field=models.CharField(blank=True, max_length=120, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='logradouro',
            field=models.CharField(blank=True, max_length=180, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bairro',
            field=models.CharField(blank=True, max_length=120, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cidade',
            field=models.CharField(blank=True, max_length=120, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='logradouro',
            field=models.CharField(blank=True, max_length=180, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
    ]
