# Generated by Django 5.2.15 on 2026-06-03 22:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_optional_address_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(db_index=True, max_length=8, verbose_name='Placa')),
                ('fipe_tipo', models.CharField(choices=[('cars', 'Carro'), ('motorcycles', 'Moto'), ('trucks', 'Caminhão')], default='cars', max_length=20, verbose_name='Tipo FIPE')),
                ('fipe_marca_codigo', models.CharField(blank=True, max_length=20, verbose_name='Código da marca FIPE')),
                ('fipe_modelo_codigo', models.CharField(blank=True, max_length=20, verbose_name='Código do modelo FIPE')),
                ('fipe_ano_codigo', models.CharField(blank=True, max_length=20, verbose_name='Código do ano/versão FIPE')),
                ('codigo_fipe', models.CharField(blank=True, max_length=20, verbose_name='Código FIPE')),
                ('mes_referencia_fipe', models.CharField(blank=True, max_length=80, verbose_name='Mês de referência FIPE')),
                ('marca', models.CharField(max_length=120, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=180, verbose_name='Modelo')),
                ('versao', models.CharField(blank=True, max_length=180, verbose_name='Versão')),
                ('qtd_portas', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Quantidade de portas')),
                ('combustivel', models.CharField(blank=True, choices=[('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('flex', 'Flex'), ('diesel', 'Diesel'), ('gnv', 'GNV'), ('eletrico', 'Elétrico'), ('hibrido', 'Híbrido'), ('outro', 'Outro')], max_length=30, verbose_name='Combustível')),
                ('km', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='KM')),
                ('chassi', models.CharField(blank=True, max_length=17, verbose_name='Chassi')),
                ('tipo_direcao', models.CharField(blank=True, choices=[('mecanica', 'Mecânica'), ('hidraulica', 'Hidráulica'), ('eletrica', 'Elétrica'), ('eletro_hidraulica', 'Eletro-hidráulica'), ('assistida', 'Assistida'), ('outra', 'Outra')], max_length=30, verbose_name='Tipo de direção')),
                ('ar_condicionado', models.BooleanField(default=False, verbose_name='Tem ar condicionado?')),
                ('modificado', models.BooleanField(default=False, verbose_name='É modificado?')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo?')),
                ('excluido_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='core.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['placa'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True), ('excluido_em__isnull', True)), fields=('placa',), name='unique_active_vehicle_placa')],
            },
        ),
    ]
