# Generated by ChatGPT for MotorMind.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='URL de destino')),
                ('nivel', models.CharField(choices=[('info', 'Informação'), ('success', 'Sucesso'), ('warning', 'Atenção'), ('error', 'Erro')], default='info', max_length=20, verbose_name='Nível')),
                ('categoria', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='Categoria')),
                ('lida_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Lida em')),
                ('exibida_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Exibida em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criada em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_app', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação interna',
                'verbose_name_plural': 'Notificações internas',
                'ordering': ['-criado_em', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='appnotification',
            index=models.Index(fields=['usuario', 'lida_em', '-criado_em'], name='core_appnot_usuario_a33e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='appnotification',
            index=models.Index(fields=['usuario', 'exibida_em', '-criado_em'], name='core_appnot_usuario_81be83_idx'),
        ),
    ]
