# Generated by Django 5.2.15 on 2026-06-08 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug')),
                ('resumo', models.CharField(blank=True, max_length=200, verbose_name='Resumo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, help_text='Emoji opcional exibido no cartão. Ex.: 🔧', max_length=8, verbose_name='Ícone (emoji)')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='site/servicos/', verbose_name='Imagem')),
                ('ordem', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordem')),
                ('destaque', models.BooleanField(db_index=True, default=False, verbose_name='Destacar na home?')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Serviço (site)',
                'verbose_name_plural': 'Serviços (site)',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(default='Automecânica Bandeirantes Multimarcas', max_length=120, verbose_name='Nome')),
                ('slogan', models.CharField(blank=True, default='Multimarcas com confiança e qualidade', max_length=180, verbose_name='Slogan')),
                ('sobre', models.TextField(blank=True, help_text='Texto institucional exibido na página Sobre e na home.', verbose_name='Sobre a oficina')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('telefone_principal', models.CharField(blank=True, default='(11) 98821-2625', max_length=20, verbose_name='Telefone principal')),
                ('telefone_secundario', models.CharField(blank=True, default='(11) 98829-2505', max_length=20, verbose_name='Telefone secundário')),
                ('whatsapp', models.CharField(blank=True, default='5511988212625', help_text='Número usado nos botões de WhatsApp. Ex.: 5511988212625.', max_length=20, verbose_name='WhatsApp (somente dígitos com DDD)')),
                ('email_contato', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de contato')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=120, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, default='São Paulo', max_length=120, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, default='SP', max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('horario_semana', models.CharField(blank=True, default='08h às 18h', max_length=120, verbose_name='Horário (seg-sex)')),
                ('horario_sabado', models.CharField(blank=True, default='08h às 12h', max_length=120, verbose_name='Horário (sábado)')),
                ('horario_domingo', models.CharField(blank=True, default='Fechado', max_length=120, verbose_name='Horário (domingo)')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('google_maps_embed', models.URLField(blank=True, help_text='Cole aqui o endereço "src" do iframe de incorporação do Google Maps.', verbose_name='URL de incorporação do Google Maps')),
                ('hero_titulo', models.CharField(blank=True, default='Cuidamos do seu carro como se fosse nosso', max_length=180, verbose_name='Título do hero')),
                ('hero_subtitulo', models.CharField(blank=True, default='Mecânica geral multimarcas com diagnóstico preciso, peças de qualidade e atendimento honesto.', max_length=240, verbose_name='Subtítulo do hero')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração do site',
                'verbose_name_plural': 'Configurações do site',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=120, verbose_name='Cliente')),
                ('texto', models.TextField(verbose_name='Depoimento')),
                ('nota', models.PositiveSmallIntegerField(default=5, verbose_name='Nota (1 a 5)')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo?')),
                ('ordem', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('resumo', models.CharField(blank=True, max_length=300, verbose_name='Resumo')),
                ('conteudo', models.TextField(help_text='Aceita HTML simples.', verbose_name='Conteúdo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='site/blog/', verbose_name='Imagem de destaque')),
                ('publicado', models.BooleanField(db_index=True, default=False, verbose_name='Publicado?')),
                ('publicado_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Publicado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_blog', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Artigo do blog',
                'verbose_name_plural': 'Artigos do blog',
                'ordering': ['-publicado_em', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('veiculo', models.CharField(blank=True, help_text='Marca, modelo e ano.', max_length=180, verbose_name='Veículo')),
                ('placa', models.CharField(blank=True, max_length=10, verbose_name='Placa')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_contato', 'Em contato'), ('concluido', 'Concluído'), ('descartado', 'Descartado')], db_index=True, default='novo', max_length=20, verbose_name='Status')),
                ('origem', models.CharField(blank=True, default='site', max_length=40, verbose_name='Origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Recebido em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='website.publicservice', verbose_name='Serviço de interesse')),
            ],
            options={
                'verbose_name': 'Pedido de orçamento',
                'verbose_name_plural': 'Pedidos de orçamento',
                'ordering': ['-criado_em'],
            },
        ),
    ]
