# Generated by ChatGPT for MotorMind.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_seed_blog_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail público de contato'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_oficina',
            field=models.EmailField(blank=True, help_text='E-mail interno que receberá pedidos de orçamento enviados pelo site.', max_length=254, verbose_name='E-mail da oficina'),
        ),
    ]
