# Generated by Django 5.2.15 on 2026-06-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_sitesettings_email_oficina'),
        ('website', '0004_sitesettings_razao_social'),
    ]

    operations = [
    ]
