# Generated by Django 5.2.15 on 2026-06-09 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_merge_20260609_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='razao_social',
        ),
    ]
