# Generated by Django 5.2.15 on 2026-06-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_sitesettings_google_maps_embed_length'),
        ('website', '0006_remove_sitesettings_razao_social'),
    ]

    operations = [
    ]
