# Generated by Django 5.2.15 on 2026-06-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_merge_20260610_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='google_maps_embed',
            field=models.URLField(blank=True, help_text='Cole aqui o endereco src do iframe de incorporacao do Google Maps.', max_length=2000, verbose_name='URL de incorporação do Google Maps'),
        ),
    ]
