# Generated by Django 5.2.15 on 2026-06-03 15:42

import accounts.managers
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('adm', 'Administrativo'), ('atendente', 'Atendente'), ('tecnico', 'Técnico'), ('financeiro', 'Financeiro'), ('estoque', 'Estoque')], default='atendente', max_length=20, verbose_name='Função')),
                ('tipo_pessoa', models.CharField(choices=[('fisica', 'Pessoa física'), ('juridica', 'Pessoa jurídica')], default='fisica', max_length=10, verbose_name='Tipo de pessoa')),
                ('nome_razao_social', models.CharField(max_length=180, verbose_name='Nome / Razão social')),
                ('documento', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CPF / CNPJ')),
                ('data_nascimento_fundacao', models.DateField(blank=True, null=True, verbose_name='Nascimento / Fundação')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=180, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=120, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=120, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('aceita_marketing', models.BooleanField(default=False, verbose_name='Aceita marketing?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome_razao_social', 'email'],
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
