# Generated by Django 5.2.15 on 2026-06-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email informado')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='Falhas consecutivas')),
                ('first_failure_at', models.DateTimeField(blank=True, null=True, verbose_name='Primeira falha da janela')),
                ('last_failure_at', models.DateTimeField(blank=True, null=True, verbose_name='Última falha')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado até')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tentativa de login',
                'verbose_name_plural': 'Tentativas de login',
                'ordering': ['-last_failure_at', 'email'],
                'constraints': [models.UniqueConstraint(fields=('email', 'ip_address'), name='unique_login_attempt_email_ip')],
            },
        ),
    ]
