# Generated by Django 5.2.15 on 2026-06-08 12:36

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_ai_field_specific_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='api_key',
            field=core.encryption.EncryptedTextField(blank=True, default='', verbose_name='Chave de API'),
        ),
    ]
