# Generated by Django 5.2.15 on 2026-06-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_alter_aisettings_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinteractionlog',
            name='acao',
            field=models.CharField(choices=[('improve_problem', 'Melhorar problema relatado'), ('improve_diagnosis', 'Melhorar diagnóstico'), ('suggest_observation', 'Sugerir observação pertinente'), ('improve_message', 'Melhorar mensagem/template'), ('email_template', 'Gerar template de email'), ('whatsapp_template', 'Gerar template de WhatsApp'), ('blog_article', 'Gerar artigo de blog'), ('general', 'Ajuda geral')], max_length=40, verbose_name='Ação'),
        ),
    ]
