# Generated by Django 5.2.15 on 2026-06-08 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data')),
                ('categoria', models.CharField(choices=[('autenticacao', 'Autenticação'), ('dados', 'Dados'), ('navegacao', 'Navegação'), ('acao', 'Ação')], db_index=True, max_length=20, verbose_name='Categoria')),
                ('acao', models.CharField(choices=[('login', 'Login'), ('login_falha', 'Falha de login'), ('logout', 'Logout'), ('criar', 'Criação'), ('editar', 'Alteração'), ('excluir', 'Exclusão lógica'), ('restaurar', 'Restauração'), ('excluir_fisico', 'Exclusão física'), ('acesso', 'Acesso'), ('acao', 'Ação')], db_index=True, max_length=20, verbose_name='Ação')),
                ('usuario_email', models.CharField(blank=True, db_index=True, max_length=254, verbose_name='Email do usuário')),
                ('objeto_app', models.CharField(blank=True, max_length=100, verbose_name='App')),
                ('objeto_modelo', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Modelo')),
                ('objeto_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID do objeto')),
                ('objeto_descricao', models.CharField(blank=True, max_length=255, verbose_name='Objeto')),
                ('descricao', models.CharField(blank=True, max_length=300, verbose_name='Descrição')),
                ('alteracoes', models.JSONField(blank=True, default=dict, verbose_name='Alterações')),
                ('caminho', models.CharField(blank=True, max_length=255, verbose_name='Caminho')),
                ('metodo', models.CharField(blank=True, max_length=10, verbose_name='Método')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Status HTTP')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User agent')),
                ('metadados', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['categoria', 'acao'], name='audit_audit_categor_8f4056_idx'), models.Index(fields=['objeto_modelo', 'objeto_id'], name='audit_audit_objeto__f54f8a_idx'), models.Index(fields=['usuario', '-criado_em'], name='audit_audit_usuario_20a78c_idx')],
            },
        ),
    ]
