# Generated by ChatGPT on 2026-06-03

from decimal import Decimal, ROUND_HALF_UP

from django.core.validators import MinValueValidator
from django.db import migrations, models


def _to_int(value, minimum=1):
    if value is None:
        return minimum
    decimal_value = Decimal(str(value))
    integer_value = int(decimal_value.to_integral_value(rounding=ROUND_HALF_UP))
    return max(integer_value, minimum)


def normalize_service_part_quantities(apps, schema_editor):
    ServiceDefaultPart = apps.get_model('operations', 'ServiceDefaultPart')
    for part in ServiceDefaultPart.objects.all().only('pk', 'quantidade'):
        part.quantidade = _to_int(part.quantidade, minimum=1)
        part.save(update_fields=['quantidade'])


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('stock', '0003_integer_quantities'),
    ]

    operations = [
        migrations.RunPython(normalize_service_part_quantities, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='servicedefaultpart',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)], verbose_name='Quantidade padrão'),
        ),
    ]
