# Generated by ChatGPT on 2026-06-03

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_integer_default_part_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo?')),
                ('excluido_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo', models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=180, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('desconto_percentual', models.DecimalField(blank=True, decimal_places=2, help_text='Informe de 0 a 100. Campo opcional.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Desconto percentual')),
            ],
            options={
                'verbose_name': 'Combo de serviços',
                'verbose_name_plural': 'Combos de serviços',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ServiceComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_associados', to='operations.servicecombo', verbose_name='Combo')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combo_associations', to='operations.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Serviço do combo',
                'verbose_name_plural': 'Serviços do combo',
                'ordering': ['service__nome'],
            },
        ),
        migrations.AddField(
            model_name='servicecombo',
            name='servicos',
            field=models.ManyToManyField(blank=True, related_name='combos_associados', through='operations.ServiceComboItem', to='operations.service', verbose_name='Serviços associados'),
        ),
        migrations.AddConstraint(
            model_name='servicecombo',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('excluido_em__isnull', True)), fields=('nome',), name='unique_active_service_combo_name'),
        ),
        migrations.AddConstraint(
            model_name='servicecomboitem',
            constraint=models.UniqueConstraint(fields=('combo', 'service'), name='unique_service_combo_service'),
        ),
    ]
