# Generated by Django 5.2.15 on 2026-06-03 22:44

import core.money
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vehicle'),
        ('operations', '0003_servicecombo_servicecomboitem'),
        ('stock', '0003_integer_quantities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo?')),
                ('excluido_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo', models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Código')),
                ('status', models.CharField(choices=[('orcamento', 'Orçamento'), ('aberta', 'Aberta'), ('em_execucao', 'Em execução'), ('aguardando_pecas', 'Aguardando peças'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], db_index=True, default='aberta', max_length=30, verbose_name='Status')),
                ('data_abertura', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data de abertura')),
                ('previsao_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Previsão de entrega')),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de finalização')),
                ('km_atual', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='KM atual')),
                ('problema_relatado', models.TextField(verbose_name='Problema relatado')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('desconto_percentual', models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Informe de 0 a 100.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Desconto percentual')),
                ('estoque_baixado', models.BooleanField(db_index=True, default=False, verbose_name='Estoque baixado?')),
                ('estoque_baixado_em', models.DateTimeField(blank=True, null=True, verbose_name='Estoque baixado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='core.customer', verbose_name='Cliente')),
                ('estoque_baixado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas_estoque_os', to=settings.AUTH_USER_MODEL, verbose_name='Estoque baixado por')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='core.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Ordem de serviço',
                'verbose_name_plural': 'Ordens de serviço',
                'ordering': ['-data_abertura', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('valor_unitario', core.money.MoneyField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor unitário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_os', to='operations.servicecombo', verbose_name='Combo')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos_os', to='operations.workorder', verbose_name='OS')),
            ],
            options={
                'verbose_name': 'Combo da OS',
                'verbose_name_plural': 'Combos da OS',
                'ordering': ['combo__nome'],
                'constraints': [models.UniqueConstraint(fields=('ordem_servico', 'combo'), name='unique_work_order_combo')],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('valor_unitario', core.money.MoneyField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor unitário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_os', to='stock.inventoryitem', verbose_name='Peça/Insumo')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_os', to='operations.workorder', verbose_name='OS')),
            ],
            options={
                'verbose_name': 'Peça/Insumo da OS',
                'verbose_name_plural': 'Peças/Insumos da OS',
                'ordering': ['item__nome'],
                'constraints': [models.UniqueConstraint(fields=('ordem_servico', 'item'), name='unique_work_order_part')],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('valor_unitario', core.money.MoneyField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor unitário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_os', to='operations.workorder', verbose_name='OS')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_os', to='operations.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Serviço da OS',
                'verbose_name_plural': 'Serviços da OS',
                'ordering': ['service__nome'],
                'constraints': [models.UniqueConstraint(fields=('ordem_servico', 'service'), name='unique_work_order_service')],
            },
        ),
    ]
