# Generated by ChatGPT on 2026-06-03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_workorder_workordercomboitem_workorderpartitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_estimativa_dias', models.PositiveIntegerField(default=7, help_text='Quantidade de dias somada à data atual para preencher automaticamente a previsão de entrega da OS.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)], verbose_name='Prazo padrão da OS em dias')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração de OS',
                'verbose_name_plural': 'Configurações de OS',
            },
        ),
    ]
