# Generated by Django 5.2.15 on 2026-06-03 23:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vehicle'),
        ('operations', '0005_workordersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo?')),
                ('excluido_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo', models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Código')),
                ('data_checkin', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data do check-in')),
                ('km', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='KM no check-in')),
                ('nivel_combustivel', models.CharField(blank=True, choices=[('vazio', 'Vazio'), ('1_4', '1/4'), ('1_2', '1/2'), ('3_4', '3/4'), ('cheio', 'Cheio')], max_length=20, verbose_name='Nível de combustível')),
                ('possui_estepe', models.BooleanField(default=False, verbose_name='Possui estepe?')),
                ('possui_macaco', models.BooleanField(default=False, verbose_name='Possui macaco?')),
                ('possui_chave_roda', models.BooleanField(default=False, verbose_name='Possui chave de roda?')),
                ('possui_documento', models.BooleanField(default=False, verbose_name='Documento do veículo presente?')),
                ('objetos_deixados', models.TextField(blank=True, verbose_name='Objetos deixados no veículo')),
                ('avarias_observadas', models.TextField(blank=True, verbose_name='Avarias observadas')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações gerais')),
                ('email_enviado', models.BooleanField(db_index=True, default=False, verbose_name='PDF enviado ao cliente?')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='PDF enviado em')),
                ('email_erro', models.TextField(blank=True, verbose_name='Erro no envio do email')),
                ('cliente', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='checkins_veiculo', to='core.customer', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('email_enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_enviados', to=settings.AUTH_USER_MODEL, verbose_name='PDF enviado por')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='operations.workorder', verbose_name='Ordem de serviço')),
                ('veiculo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='core.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Check-in de veículo',
                'verbose_name_plural': 'Check-ins de veículos',
                'ordering': ['-data_checkin', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='VehicleCheckInPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='checkins/%Y/%m/', verbose_name='Foto')),
                ('legenda', models.CharField(blank=True, max_length=180, verbose_name='Legenda')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='operations.vehiclecheckin', verbose_name='Check-in')),
            ],
            options={
                'verbose_name': 'Foto do check-in',
                'verbose_name_plural': 'Fotos do check-in',
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='vehiclecheckin',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('excluido_em__isnull', True)), fields=('ordem_servico',), name='unique_active_checkin_per_work_order'),
        ),
    ]
