# Generated by ChatGPT on 2026-06-04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


STATUS_CHOICES = [
    ('orcamento', 'Orçamento'),
    ('diagnostico', 'Diagnóstico'),
    ('aguardando_aprovacao', 'Aguardando aprovação'),
    ('aprovada', 'Aprovada'),
    ('em_execucao', 'Em execução'),
    ('aguardando_peca', 'Aguardando peça'),
    ('pronta', 'Pronta'),
    ('pronto_para_retirar', 'Pronto para retirar'),
    ('entregue', 'Entregue'),
    ('cancelada', 'Cancelada'),
]


def normalize_existing_statuses(apps, schema_editor):
    WorkOrder = apps.get_model('operations', 'WorkOrder')
    mapping = {
        'aberta': 'diagnostico',
        'aguardando_pecas': 'aguardando_peca',
        'finalizada': 'pronta',
    }
    for old_status, new_status in mapping.items():
        WorkOrder.objects.filter(status=old_status).update(status=new_status)


def reverse_normalize_existing_statuses(apps, schema_editor):
    WorkOrder = apps.get_model('operations', 'WorkOrder')
    mapping = {
        'diagnostico': 'aberta',
        'aguardando_peca': 'aguardando_pecas',
        'pronta': 'finalizada',
    }
    for old_status, new_status in mapping.items():
        WorkOrder.objects.filter(status=old_status).update(status=new_status)


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_vehiclecheckin_vehiclecheckinphoto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(normalize_existing_statuses, reverse_normalize_existing_statuses),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=STATUS_CHOICES, db_index=True, default='orcamento', max_length=30, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='WorkOrderStatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=STATUS_CHOICES, max_length=30, verbose_name='Status anterior')),
                ('status_novo', models.CharField(choices=STATUS_CHOICES, max_length=30, verbose_name='Novo status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transicoes_status_os', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicoes_status', to='operations.workorder', verbose_name='OS')),
            ],
            options={
                'verbose_name': 'Transição de status da OS',
                'verbose_name_plural': 'Transições de status da OS',
                'ordering': ['-criado_em', '-pk'],
            },
        ),
    ]
