# Generated by ChatGPT on 2026-06-04

from django.db import migrations, models


STATUS_CHOICES = [
    ('aberta', 'Aberta'),
    ('diagnostico', 'Diagnóstico'),
    ('orcamento', 'Orçamento'),
    ('aguardando_aprovacao', 'Aguardando aprovação'),
    ('aprovada', 'Aprovada'),
    ('em_execucao', 'Em execução'),
    ('aguardando_peca', 'Aguardando peça'),
    ('em_teste', 'Em teste'),
    ('pronta', 'Pronta'),
    ('pronto_para_retirar', 'Pronto para retirar'),
    ('entregue', 'Entregue'),
    ('cancelada', 'Cancelada'),
    ('arquivada', 'Arquivada'),
]


def normalize_legacy_statuses(apps, schema_editor):
    WorkOrder = apps.get_model('operations', 'WorkOrder')
    mapping = {
        'aguardando_pecas': 'aguardando_peca',
        'finalizada': 'pronta',
    }
    for old_status, new_status in mapping.items():
        WorkOrder.objects.filter(status=old_status).update(status=new_status)


def reverse_normalize_legacy_statuses(apps, schema_editor):
    WorkOrder = apps.get_model('operations', 'WorkOrder')
    mapping = {
        'aguardando_peca': 'aguardando_pecas',
        'pronta': 'finalizada',
    }
    for old_status, new_status in mapping.items():
        WorkOrder.objects.filter(status=old_status).update(status=new_status)


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_workorder_state_machine'),
    ]

    operations = [
        migrations.RunPython(normalize_legacy_statuses, reverse_normalize_legacy_statuses),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=STATUS_CHOICES, db_index=True, default='aberta', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='workorderstatustransition',
            name='status_anterior',
            field=models.CharField(choices=STATUS_CHOICES, max_length=30, verbose_name='Status anterior'),
        ),
        migrations.AlterField(
            model_name='workorderstatustransition',
            name='status_novo',
            field=models.CharField(choices=STATUS_CHOICES, max_length=30, verbose_name='Novo status'),
        ),
    ]
