# Generated by Django 5.2.15 on 2026-06-04 02:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_workorder_refined_state_machine'),
        ('stock', '0003_integer_quantities'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderStockRequirementOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(help_text='Quantidade efetiva que será considerada na baixa de estoque desta OS.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade ajustada')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_pecas_previstas_os', to='stock.inventoryitem', verbose_name='Peça/Insumo')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_pecas_previstas', to='operations.workorder', verbose_name='OS')),
            ],
            options={
                'verbose_name': 'Ajuste de peça prevista da OS',
                'verbose_name_plural': 'Ajustes de peças previstas da OS',
                'ordering': ['item__nome'],
                'constraints': [models.UniqueConstraint(fields=('ordem_servico', 'item'), name='unique_work_order_stock_requirement_override')],
            },
        ),
    ]
