# Generated by ChatGPT on 2026-06-04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_workorder_stock_requirement_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordersettings',
            name='vagas_oficina',
            field=models.PositiveIntegerField(
                default=5,
                help_text='Quantidade máxima de veículos/OS que podem ocupar vaga física simultaneamente na oficina.',
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)],
                verbose_name='Vagas da oficina',
            ),
        ),
    ]
