# Generated by Django 5.2.15 on 2026-06-04 14:50

import core.money
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_workshop_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderApprovalBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Versão')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Token público')),
                ('status', models.CharField(choices=[('pending', 'Aguardando resposta'), ('approved', 'Aprovado integralmente'), ('partially_approved', 'Aprovado parcialmente'), ('rejected', 'Recusado integralmente'), ('superseded', 'Substituído')], db_index=True, default='pending', max_length=30, verbose_name='Status')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot geral')),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Desconto percentual')),
                ('subtotal_snapshot', core.money.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Subtotal snapshot')),
                ('valor_desconto_snapshot', core.money.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Desconto snapshot')),
                ('valor_total_snapshot', core.money.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total snapshot')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('email_enviado', models.BooleanField(db_index=True, default=False, verbose_name='Email enviado?')),
                ('email_erro', models.TextField(blank=True, verbose_name='Erro de email')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_os_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_os_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos_aprovacao', to='operations.workorder', verbose_name='OS')),
            ],
            options={
                'verbose_name': 'Orçamento versionado da OS',
                'verbose_name_plural': 'Orçamentos versionados da OS',
                'ordering': ['-versao', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderApprovalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisao', models.CharField(choices=[('approve_all', 'Aprovar tudo'), ('approve_partial', 'Aprovar parcialmente'), ('reject_all', 'Recusar tudo')], db_index=True, max_length=30, verbose_name='Decisão')),
                ('metodo', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('presential', 'Cliente presencialmente'), ('shop', 'Oficina')], db_index=True, max_length=30, verbose_name='Método')),
                ('nome_responsavel', models.CharField(max_length=180, verbose_name='Responsável')),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='Documento informado')),
                ('documento_valido', models.BooleanField(default=False, verbose_name='Documento válido?')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('local', models.CharField(blank=True, max_length=180, verbose_name='Local')),
                ('itens_aprovados_snapshot', models.JSONField(blank=True, default=list, verbose_name='Itens aprovados')),
                ('itens_rejeitados_snapshot', models.JSONField(blank=True, default=list, verbose_name='Itens rejeitados')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('usuario_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_aprovacao_os', to=settings.AUTH_USER_MODEL, verbose_name='Usuário interno')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='operations.workorderapprovalbudget', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Auditoria de aprovação de orçamento',
                'verbose_name_plural': 'Auditorias de aprovação de orçamento',
                'ordering': ['-criado_em', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderApprovalBudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('service', 'Serviço'), ('combo', 'Combo'), ('part', 'Peça/Insumo')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('referencia_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID de referência')),
                ('codigo', models.CharField(blank=True, max_length=40, verbose_name='Código/SKU')),
                ('nome', models.CharField(max_length=220, verbose_name='Nome')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('quantidade_base', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade base')),
                ('valor_unitario', core.money.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor unitário')),
                ('subtotal', core.money.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Subtotal')),
                ('origem_tipo', models.CharField(blank=True, max_length=60, verbose_name='Tipo de origem')),
                ('origem_codigo', models.CharField(blank=True, max_length=40, verbose_name='Código de origem')),
                ('origem_nome', models.CharField(blank=True, max_length=220, verbose_name='Nome da origem')),
                ('origem_observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação da origem')),
                ('aprovado', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Aprovado?')),
                ('respondido_em', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='operations.workorderapprovalbudget', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Item do orçamento versionado',
                'verbose_name_plural': 'Itens do orçamento versionado',
                'ordering': ['tipo', 'nome', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='workorderapprovalbudget',
            constraint=models.UniqueConstraint(fields=('ordem_servico', 'versao'), name='unique_work_order_approval_budget_version'),
        ),
        migrations.AddIndex(
            model_name='workorderapprovalbudgetitem',
            index=models.Index(fields=['orcamento', 'tipo', 'aprovado'], name='operations__orcamen_77b62d_idx'),
        ),
    ]
