# Generated by MotorMind assistant on 2026-06-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0014_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='tecnico_responsavel',
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='ordens_servico_responsavel',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Técnico responsável',
            ),
        ),
    ]
