# Generated by ChatGPT for MotorMindv8.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_workorder_tecnico_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedefaultpart',
            name='obrigatoria',
            field=models.BooleanField(default=True, help_text='Peças obrigatórias acompanham o serviço. Se forem recusadas no orçamento, o serviço inteiro é recusado.', verbose_name='Obrigatória?'),
        ),
        migrations.AddField(
            model_name='workorderapprovalbudgetitem',
            name='hierarquia_ordem',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ordem hierárquica'),
        ),
        migrations.AddField(
            model_name='workorderapprovalbudgetitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='operations.workorderapprovalbudgetitem', verbose_name='Item pai'),
        ),
        migrations.AddField(
            model_name='workorderapprovalbudgetitem',
            name='peca_obrigatoria',
            field=models.BooleanField(default=True, help_text='Usado para peças vinculadas a serviço/combo. Peças obrigatórias recusadas reprovam o item pai.', verbose_name='Peça obrigatória?'),
        ),
        migrations.AlterModelOptions(
            name='workorderapprovalbudgetitem',
            options={'ordering': ['hierarquia_ordem', 'pk'], 'verbose_name': 'Item do orçamento versionado', 'verbose_name_plural': 'Itens do orçamento versionado'},
        ),
    ]
