# Generated by Django 5.2.15 on 2026-06-09 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vehicle'),
        ('operations', '0017_repair_approval_budget_item_hierarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerVehicleAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Token público')),
                ('placa', models.CharField(db_index=True, max_length=8, verbose_name='Placa solicitada')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de envio')),
                ('codigo_hash', models.CharField(max_length=128, verbose_name='Hash do código')),
                ('tentativas', models.PositiveSmallIntegerField(default=0, verbose_name='Tentativas')),
                ('expira_em', models.DateTimeField(db_index=True, verbose_name='Expira em')),
                ('verificado_em', models.DateTimeField(blank=True, null=True, verbose_name='Verificado em')),
                ('revogado_em', models.DateTimeField(blank=True, null=True, verbose_name='Revogado em')),
                ('ip_solicitacao', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da solicitação')),
                ('user_agent_solicitacao', models.TextField(blank=True, verbose_name='User agent da solicitação')),
                ('ip_verificacao', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da verificação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_acesso_historico_veiculo', to='core.customer', verbose_name='Cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_acesso_historico', to='core.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Token de acesso ao histórico do veículo',
                'verbose_name_plural': 'Tokens de acesso ao histórico do veículo',
                'ordering': ['-criado_em', '-pk'],
                'indexes': [models.Index(fields=['token', 'expira_em'], name='operations__token_ed6961_idx'), models.Index(fields=['placa', 'email'], name='operations__placa_6936f9_idx')],
            },
        ),
    ]
