# Generated by ChatGPT for MotorMindv8.

from decimal import Decimal

from django.db import migrations

import core.money


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_customervehicleaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='custo',
            field=core.money.MoneyField(
                default=Decimal('0.00'),
                help_text='Custo interno da mão de obra/execução. Não é cobrado diretamente do cliente.',
                verbose_name='Custo do serviço',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='valor',
            field=core.money.MoneyField(default=Decimal('0.00'), verbose_name='Valor do serviço'),
        ),
    ]
